implmented checkout

diff --git a/tigger-init b/tigger-init
--- a/tigger-init
+++ b/tigger-init
@@ -7,10 +7,10 @@ if [ -d .tigger ]; then
 fi
 
 # raise error if the .git folder exists
-# if [ -d .git ]; then
-#     >&2 echo tigger-init: error: can not run tigger because .git present in current directory
-#     exit 1
-# fi
+if [ -d .git ]; then
+    >&2 echo "tigger-init: error: can not run tigger because .git present in current directory"
+    exit 1
+fi
 
 # create a .tigger directory
 mkdir .tigger
