31/32 autotests

diff --git a/tigger-branch b/tigger-branch
--- a/tigger-branch
+++ b/tigger-branch
@@ -15,9 +15,7 @@ fi
 # Create variables to access directories
 
 BRANCH="$(find .tigger/branches/.head/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"
-
-CURRENTCOMMIT=$(cat .tigger/branches/"$BRANCH"/.commitindex)
-
+CURRENTCOMMIT="$(tail -1 < .tigger/branches/"$BRANCH"/.commitindex 2>/dev/null)"
 
 # check if flags are correct
 if echo "$1" | grep -Ei '^-[^d]' >/dev/null; then
@@ -41,56 +39,96 @@ elif [ "$1" = -d ] && [ "$#" -eq 2 ]; then
 
     #check the that selected branch isn't master
     if [ "$TARGETBRANCH" = "master" ]; then
-        1>&2 echo "tigger-branch: error: can not delete branch 'master'"
+        echo "tigger-branch: error: can not delete branch 'master'"
         exit 1
     fi
+
+    
+    #cannot delete current head
+    if [ "$TARGETBRANCH" = .tigger/branches/.head/"$TARGETBRANCH" ]; then
+        echo "tigger-branch: error: internal error error: Cannot delete branch '$TARGETBRANCH'"
+        exit 1
+    fi
+
+
     # check the that selected branch exists
     if ! [ -d .tigger/branches/"$TARGETBRANCH" ]; then
         echo "tigger-branch: error: branch '$TARGETBRANCH' doesn't exist"
         exit 1
     fi
 
+
+        # unmerged changes
+    TARGETCOMMIT=$( tail -1 < .tigger/branches/"$TARGETBRANCH"/.commitindex )
+    SHAREDCOMMIT=""
+    for COMMITS in .tigger/commits/*; do
+        COMMITINDEX=$(basename "$COMMITS")
+        if grep -Fx "$COMMITINDEX" .tigger/branches/"$BRANCH"/.commitindex >/dev/null; then
+            if grep -Fx "$COMMITINDEX" .tigger/branches/"$TARGETBRANCH"/.commitindex >/dev/null; then
+                SHAREDCOMMIT=0
+         
+            fi
+        else 
+        SHAREDCOMMIT=1
+        fi
+    done
+
+    if [ -n "$SHAREDCOMMIT" ]; then
+        if [ "$SHAREDCOMMIT" -eq 1 ]; then
+            for file in .tigger/branches/"$TARGETBRANCH"/*; do
+                CURRFILE=$(basename "$file")
+                if ! cmp -s .tigger/branches/"$BRANCH"/"$CURRFILE" .tigger/commits/"$TARGETCOMMIT"/"$CURRFILE"; then
+                    echo "tigger-branch: error: branch '$TARGETBRANCH' has unmerged changes"
+                    exit 1
+                fi
+            done
+        fi
+    fi
+
     # delete the branch from the branches directory
     rm -r .tigger/branches/"$TARGETBRANCH"
  
-    # remove each index
-    for index in $(find .tigger/index/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \;); do
-    if echo "$index" | grep -E "^(."$TARGETINDEX".[0-9]*)" >/dev/null; then
+    # creates a list of filenames and store in a tempfile this was done to kepe shellcheck happy
+    TEMPFILE="$(mktemp)"
+    find .tigger/index/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \; > "$TEMPFILE"
+
+    while read -r index; do
+    if echo "$index" | grep -E "^(.$TARGETINDEX.[0-9]*)" >/dev/null; then
        rm -r .tigger/index/"$index"
     fi
-    done
+    done < "$TEMPFILE"
     echo "Deleted branch '$TARGETBRANCH'"
-
+    rm -r "$TEMPFILE"
+# create branch
 elif [ "$#" -eq 1 ]; then
 
+    # error checking
     TARGETBRANCH="$1"
-    
+    # first character of branch cannot be _ or .
     if echo "$TARGETBRANCH" | grep -Ei '^([_]|[.])' >/dev/null; then
         echo "tigger-branch: error: invalid filename '$TARGETBRANCH'"
         exit 1
     fi
-
+    # a branch cannot be all numbers
     if echo "$TARGETBRANCH" | grep -Ei '^([0-9]*)$' >/dev/null; then
         echo "tigger-branch: error: invalid filename '$TARGETBRANCH'"
         exit 1
     fi
-
+    # bad characters
     if echo "$TARGETBRANCH" | grep -Ei '[^a-z0-9_.-]' >/dev/null; then
         echo "tigger-branch: error: invalid filename '$TARGETBRANCH'"
         exit 1
     fi
-
-
+    # check if branc already exists
     if  [ -d .tigger/branches/"$TARGETBRANCH" ]; then
         echo "tigger-branch: error: branch '$1' already exists"
         exit 1
     fi
 
-
-    # make a new branch
+    # make a new branch 
     mkdir -p .tigger/branches/"$TARGETBRANCH"
     mkdir -p .tigger/index/."$TARGETBRANCH".0
-    
+
     cp -r .tigger/commits/"$CURRENTCOMMIT"/* .tigger/branches/"$TARGETBRANCH"/
     # add the files to be ready to commited
     cp -r .tigger/commits/"$CURRENTCOMMIT"/* .tigger/index/."$TARGETBRANCH".0
diff --git a/tigger-checkout b/tigger-checkout
--- a/tigger-checkout
+++ b/tigger-checkout
@@ -38,59 +38,119 @@ fi
 # Create variables specific for the target branch
 TARGETBRANCH="$1"
 TARGETBRANCHINDEX=$(cat .tigger/branches/"$TARGETBRANCH"/.branchindex)
-CURRENTCOMMIT=$(cat .tigger/branches/"$TARGETBRANCH"/.commitindex)
+TARGETCOMMIT=$( tail -1 < .tigger/branches/"$TARGETBRANCH"/.commitindex ) 2>/dev/null
+CURRENTCOMMIT=$( tail -1 < .tigger/branches/"$BRANCH"/.commitindex) 2>/dev/null
 
+
+# check if the commit numbers are the same
 if ! diff .tigger/branches/"$BRANCH"/.commitindex .tigger/branches/"$TARGETBRANCH"/.commitindex >/dev/null; then
 
-    
-    # warnings
+    TEMPFILE="$(mktemp)"
+   find .tigger/commits/"$TARGETCOMMIT" -type f  -exec basename -a {} \; > "$TEMPFILE"
+
+    # error checking between commit repo and workdir files
+    while read -r file; do
+        WORKDIRCURR="$file"
+        REPOCURR=.tigger/commits/"$CURRENTCOMMIT"/"$file"
 
 
+            if [ -f "$WORKDIRCURR" ] && ! cmp -s "$WORKDIRCURR" "$REPOCURR";then
+                # creates a list of conflicts to print out
+                if [ ! -f .errormsg ]; then
+                    echo "tigger-checkout: error: Your changes to the following files would be overwritten by checkout:" > .errormsg
+                fi
+                # ammeneds the file to the list of conflicts
+                echo "$file" >> .conflicts
+            fi
+    done < "$TEMPFILE"
+    rm -r "$TEMPFILE"
+
+    TEMPFILE="$(mktemp)"
+    find .tigger/commits/"$CURRENTCOMMIT" -type f -exec basename -a {} \; > "$TEMPFILE"
+
+    # error checking the different repos
+    while read -r file; do
+
+        WORKDIRCURR="$file"
+        REPOTARGET=.tigger/commits/"$TARGETCOMMIT"/"$file"
+        REPOCURR=.tigger/commits/"$CURRENTCOMMIT"/"$file"
+        INDEXCURR=.tigger/changes/"$file"
+       
+        if [ -f "$REPOTARGET" ] && ! cmp -s "$REPOTARGET" "$REPOCURR"; then
+
+            if [ -f "$WORKDIRCURR" ] && ! cmp -s "$WORKDIRCURR" "$REPOCURR";then
+                if [ ! -f .errormsg ]; then
+                    echo "tigger-checkout: error: Your changes to the following files would be overwritten by checkout:" > .errormsg
+                fi
+                echo "$file" >> .conflicts
+            fi
+            if [ -f "$INDEXCURR" ] && ! cmp -s "$INDEXCURR" "$REPOCURR"; then
+                if [ ! -f .errormsg ]; then
+                    echo "tigger-checkout: error: Your changes to the following files would be overwritten by checkout:" > .errormsg
+                fi
+                echo "$file" >> .conflicts
+            fi
+        
+        fi
+    done < "$TEMPFILE"
+    rm -r "$TEMPFILE"
+
+    # if there was any conflicts print the message and exit
+    if [ -f .errormsg ]; then
+        sort  < .conflicts | uniq >> .errormsg
+        cat .errormsg
+        rm -r .errormsg .conflicts
+        exit 1
+    fi
+
+    TEMPFILE="$(mktemp)"
+    find .tigger/branches/"$BRANCH" -type f -exec basename -a {} \; > "$TEMPFILE"
     # Remove files from the working directory that isn't commited in the target branch
-    
-    for file in tigger/branches/"$BRANCH"/*; do
-        # check the loop worked
-        if [ ! "$file" -f ]; then
-            continue
-        else
-            file=basname (echo "$file")
-
-
-
+    while read -r file; do
         if ! [ -f .tigger/"$TARGETBRANCH"/"$file" ]; then
             rm -f "$file" 
         fi
-    done
+    done < "$TEMPFILE"
+    rm -r "$TEMPFILE"
 
+    TEMPFILE="$(mktemp)"
+    find  .tigger/branches/"$TARGETBRANCH" -type f -exec basename -a {} \; > "$TEMPFILE"
     # Add files to the target commit that might be missing or have changes
-    for file in $(basename -a $(find  .tigger/branches/"$TARGETBRANCH" -type f )); do
+    while read -r file; do
         # don't add the datafiles
         if ! [ "$file" = ".commitindex" ] && ! [ "$file" = ".branchindex" ];then
             cp .tigger/branches/"$TARGETBRANCH"/"$file" .
         fi
-    done
+    done < "$TEMPFILE"
+    rm -r "$TEMPFILE"
 fi
 
 # if there are changes in the index from other branches
 # add them to the index of the target branch
 if [ -d .tigger/changes ]; then
 
-    for file in $(basename -a $(find .tigger/changes -type f )); do
+    TEMPFILE="$(mktemp)"
+    find .tigger/changes -type f -exec basename -a {} \; > "$TEMPFILE"
+    while read -r file; do
         cp -r .tigger/changes/"$file" .tigger/index/."$TARGETBRANCH"."$TARGETBRANCHINDEX"
-    done
+    done < "$TEMPFILE"
+    rm -r "$TEMPFILE"
 else  
     rm -r .tigger/index/."$TARGETBRANCH"."$TARGETBRANCHINDEX"/* 2>/dev/null
-    cp -r cp -r .tigger/commits/"$CURRENTCOMMIT"/* .tigger/index/."$TARGETBRANCH"."$TARGETBRANCHINDEX" 2>/dev/null
+    cp -r cp -r .tigger/commits/"$TARGETCOMMIT"/* .tigger/index/."$TARGETBRANCH"."$TARGETBRANCHINDEX" 2>/dev/null
 fi
 
 mkdir -p .tigger/.headinfo
+
 cp -r .tigger/branches/.head/"$BRANCH" .tigger/.headinfo
 rm -r .tigger/branches/.head/"$BRANCH"
-if ! cp -R .tigger/.headinfo/"$TARGETBRANCH" tigger/branches/.head/ 2>/dev/null; then
-    mkdir .tigger/branches/.head/"$TARGETBRANCH" && touch .tigger/branches/.head/"$TARGETBRANCH"/0
-else
-rm -r .tigger/.headinfo/"$TARGETBRANCH"
+
+mkdir -p .tigger/branches/.head/"$TARGETBRANCH"
+cp -r .tigger/.headinfo/"$TARGETBRANCH"/.log .tigger/branches/.head/"$TARGETBRANCH" 2>/dev/null
+if ! cp -r .tigger/.headinfo/"$TARGETBRANCH"/* .tigger/branches/.head/"$TARGETBRANCH" 2>/dev/null; then
+    touch .tigger/branches/.head/"$TARGETBRANCH"/0
 fi
+
 
 echo "Switched to branch '$TARGETBRANCH'"
 
